storage:
  type: sqlite
  path: /opt/gatus/data/gatus.db

endpoints:
  - name: Proxmox pve-a2
    group: Proxmox
    url: "https://pve-a2.risk-mermaid.ts.net/"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      
  - name: Proxmox pve3
    group: Proxmox
    url: "https://pve3.risk-mermaid.ts.net/"
    interval: 5m
    conditions:
      - "[STATUS] == 200"

  - name: Proxmox pve4
    group: Proxmox
    url: "https://pve4.risk-mermaid.ts.net/"
    interval: 5m
    conditions:
      - "[STATUS] == 200"

  - name: Proxmox pve5
    group: Proxmox
    url: "https://pve5.risk-mermaid.ts.net/"
    interval: 5m
    conditions:
      - "[STATUS] == 200"

  - name: Proxmox pve6
    group: Proxmox
    url: "https://pve6.risk-mermaid.ts.net/"
    interval: 5m
    conditions:
      - "[STATUS] == 200"

  - name: PBS1
    group: Backup
    url: "https://pbs1.risk-mermaid.ts.net/"
    interval: 1m
    conditions:
      - "[STATUS] == 200"

  - name: InfluxDB
    group: Monitoring 👁️
    url: "https://influxdb1.risk-mermaid.ts.net/"
    interval: 1m
    conditions:
      - "[STATUS] == 200"

  - name: Jellyfin
    group: Media 📺
    url: "https://brandons-mac-mini.risk-mermaid.ts.net:8096/"
    interval: 3m
    conditions:
      - "[STATUS] == 200"
