storage:
  type: sqlite
  path: /opt/gatus/data/gatus.db

alerting:
  discord:
    webhook-url: $GATUS_DISCORD_WEBHOOK_URL
    default-alert:
      description: "Health check failed for {endpoint}"
      send-on-resolved: true

endpoints:
  - name: Proxmox pve-a2
    group: Proxmox
    url: "https://pve-a2.risk-mermaid.ts.net/"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      
  - name: Proxmox pve3
    group: Proxmox
    url: "https://pve3.risk-mermaid.ts.net/"
    interval: 5m
    conditions:
      - "[STATUS] == 200"

  - name: Proxmox pve4
    group: Proxmox
    url: "https://pve4.risk-mermaid.ts.net/"
    interval: 5m
    conditions:
      - "[STATUS] == 200"

  - name: Proxmox pve5
    group: Proxmox
    url: "https://pve5.risk-mermaid.ts.net/"
    interval: 5m
    conditions:
      - "[STATUS] == 200"

  - name: Proxmox pve6
    group: Proxmox
    url: "https://pve6.risk-mermaid.ts.net/"
    interval: 5m
    conditions:
      - "[STATUS] == 200"

  - name: PBS1
    group: Backup
    url: "https://pbs1.risk-mermaid.ts.net/"
    interval: 1m
    conditions:
      - "[STATUS] == 200"

  - name: InfluxDB
    group: Monitoring 👁️
    url: "https://influxdb1.risk-mermaid.ts.net/health"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[BODY].status == pass"

  - name: Jellyfin
    group: Media 📺
    url: "https://brandons-mac-mini.risk-mermaid.ts.net:8096/"
    interval: 3m
    conditions:
      - "[STATUS] == 200"

  - name: Homebridge
    group: Smart Home 🏠
    url: "https://hb1.risk-mermaid.ts.net/"
    interval: 1m
    conditions:
      - "[STATUS] == 200"

  - name: Patchmon
    group: Monitoring 👁️
    url: "https://patchmon.risk-mermaid.ts.net/"
    interval: 5m
    conditions:
      - "[STATUS] == 200"

  - name: Radarr
    group: Media 📺
    url: "https://radarr.risk-mermaid.ts.net/"
    interval: 3m
    conditions:
      - "[STATUS] == 200"

  - name: Sonarr
    group: Media 📺
    url: "https://sonarr.risk-mermaid.ts.net/"
    interval: 3m
    conditions:
      - "[STATUS] == 200"

  - name: Basement AP
    group: Infrastructure 📶
    url: "icmp://192.168.111.83"
    interval: 30s
    conditions:
      - "[CONNECTED] == true"

  - name: UniFi Dream Machine
    group: Infrastructure 📶
    url: "icmp://192.168.111.1"
    interval: 30s
    conditions:
      - "[CONNECTED] == true"

  - name: Server Rack UPS
    group: Infrastructure 📶
    url: "icmp://192.168.5.106"
    interval: 30s
    conditions:
      - "[CONNECTED] == true"

  - name: Hue lights bridge
    group: Smart Home 🏠
    url: "icmp://192.168.128.45"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

  - name: PocketID
    group: Authentication 🔐
    url: "https://auth.willjasen.net/"
    interval: 1m
    conditions:
      - "[STATUS] == 200"

  - name: TinyAuth
    group: Authentication 🔐
    url: "https://sso.willjasen.net/"
    interval: 1m
    conditions:
      - "[STATUS] == 200"

  - name: Caddy
    group: Infrastructure 📶
    url: "https://sync1.willjasen.net/"
    interval: 1m
    conditions:
      - "[STATUS] == 200"

  - name: Open WebUI
    group: AI
    url: "https://openwebui.risk-mermaid.ts.net/"
    interval: 1m
    conditions:
      - "[STATUS] == 200"

  - name: main website
    group: Websites
    url: "https://willjasen.com/"
    interval: 5m
    conditions:
      - "[STATUS] == 200"

  - name: look Google tag
    group: Websites
    url: "https://look.willjasen.com/"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[BODY] == pat(*cdn-cgi/zaraz*)"

  - name: school
    group: Websites
    url: "https://school.willjasen.com/"
    interval: 5m
    conditions:
      - "[STATUS] == 200"

  - name: family
    group: Websites
    url: "https://family.willjasen.com/"
    interval: 5m
    conditions:
      - "[STATUS] == 200"

  - name: my dna
    group: Websites
    url: "https://dna.willjasen.com/"
    interval: 5m
    conditions:
      - "[STATUS] == 200"

  - name: old website
    group: Websites
    url: "https://old.willjasen.com/"
    interval: 5m
    conditions:
      - "[STATUS] == 200"

  - name: stretchie
    group: Websites
    url: "https://stretchie.net/"
    interval: 5m
    conditions:
      - "[STATUS] == 200"

  - name: themaus.haus
    group: Websites
    url: "https://themaus.haus/"
    interval: 5m
    conditions:
      - "[STATUS] == 200"

  - name: levitate
    group: Websites
    url: "https://levitate.willjasen.com/"
    interval: 5m
    conditions:
      - "[STATUS] == 200"

  - name: nerdhirn
    group: Websites
    url: "https://nerdhirn.tech/"
    interval: 5m
    conditions:
      - "[STATUS] == 200"

  - name: tailmox
    group: Websites
    url: "https://tailmox.com/"
    interval: 5m
    conditions:
      - "[STATUS] == 200"

  - name: scummie
    group: Websites
    url: "https://scummie.netlify.app/"
    interval: 5m
    conditions:
      - "[STATUS] == 200"

  - name: Syncthing, Mac mini
    group: Services
    url: "https://brandons-mac-mini.risk-mermaid.ts.net:8384/rest/noauth/health"
    interval: 60s
    conditions:
      - "[STATUS] == 200"
      - "[BODY].status == OK"
